import Link from "next/link";
export default function AboutPage(){
return <main className="min-h-screen bg-[#fff8fc] px-4 pb-20 pt-32 text-gray-800 dark:bg-[#211627] dark:text-white"><div className="mx-auto max-w-6xl">
<section className="grid items-center gap-12 lg:grid-cols-2">
<div><span className="rounded-full border border-pink-200 bg-pink-50 px-4 py-1.5 text-xs font-bold tracking-wider text-fuchsia-600">ABOUT PP BEAUTY</span><h1 className="mt-5 text-4xl font-extrabold md:text-5xl">ความสวยที่เริ่มต้นจากการรักตัวเอง</h1><p className="mt-6 leading-relaxed text-gray-600 dark:text-purple-100/70">PP BEAUTY คือร้านเครื่องสำอางที่อยากทำให้การช้อปปิ้งความงามเป็นเรื่องง่ายและน่ารัก เราคัดสรรเครื่องสำอาง สกินแคร์ น้ำหอม และไอเทมดูแลตัวเองที่น่าสนใจมาไว้ในที่เดียว</p><p className="mt-4 leading-relaxed text-gray-600 dark:text-purple-100/70">เราเชื่อว่าไม่มีคำว่า “สวยแบบเดียว” ทุกคนสามารถเลือกสี กลิ่น และผลิตภัณฑ์ที่เข้ากับตัวเองได้อย่างสนุกและมั่นใจ</p><Link href="/#products" className="mt-7 inline-flex rounded-full bg-gradient-to-r from-pink-500 to-purple-600 px-7 py-3 font-bold text-white shadow-lg shadow-pink-500/20">เริ่มช้อปสินค้า ✨</Link></div>
<div className="rounded-[2rem] bg-gradient-to-br from-pink-100 via-white to-purple-100 p-10 shadow-xl"><div className="rounded-3xl bg-white p-8 text-center shadow-sm"><div className="text-6xl">💗</div><h2 className="mt-5 text-2xl font-bold text-gray-900">Beauty • Care • Confidence</h2><p className="mt-3 text-sm text-gray-500">ดูแลตัวเองในแบบที่ทำให้คุณรู้สึกดีที่สุด</p></div></div>
</section>
<section className="mt-20 grid gap-6 md:grid-cols-3">{[["✨","คัดสรรอย่างตั้งใจ","เลือกไอเทมที่น่าใช้และเข้ากับชีวิตประจำวัน"],["💎","ใส่ใจคุณภาพ","ให้ความสำคัญกับรายละเอียดและประสบการณ์ของลูกค้า"],["💗","เป็นตัวเองได้เต็มที่","สนับสนุนทุกสไตล์ ทุกลุค และทุกความมั่นใจ"]].map(([i,t,d])=><div key={t} className="rounded-2xl border border-pink-100 bg-white p-7 text-center shadow-sm dark:border-purple-900 dark:bg-[#2b1b35]"><div className="text-3xl">{i}</div><h3 className="mt-4 font-bold">{t}</h3><p className="mt-2 text-sm text-gray-500 dark:text-purple-100/70">{d}</p></div>)}</section>
</div></main>}
