"use client";
import {useState} from "react";
import Link from "next/link";
import Swal from "sweetalert2";
const INFO=[["💌","อีเมลซัพพอร์ต","support@ppbeauty.com","ตอบกลับภายใน 1-3 ชั่วโมง"],["💬","แชตสอบถาม","PP BEAUTY Official","ทีมงานพร้อมดูแลคุณ"],["📦","เรื่องการจัดส่ง","ติดตามสถานะคำสั่งซื้อ","สอบถามเราได้ทุกวัน"]];
const TOPICS=["สอบถามสินค้าและส่วนผสม","สอบถามสถานะคำสั่งซื้อ","แจ้งปัญหาการจัดส่ง","ขอคำแนะนำเกี่ยวกับสินค้า","ข้อเสนอแนะเกี่ยวกับเว็บไซต์"];
export default function ContactPage(){
const [loading,setLoading]=useState(false); const [form,setForm]=useState({name:"",email:"",subject:"",message:""});
const change=e=>setForm({...form,[e.target.name]:e.target.value});
const submit=async e=>{e.preventDefault();if(!form.name||!form.email||!form.message){return Swal.fire({icon:"warning",title:"ข้อมูลไม่ครบถ้วน",text:"กรุณาระบุชื่อ อีเมล และข้อความ",confirmButtonColor:"#d946ef"});}setLoading(true);await new Promise(r=>setTimeout(r,700));setLoading(false);await Swal.fire({icon:"success",title:"ส่งข้อความสำเร็จ",text:"ทีมงานได้รับข้อความของคุณแล้ว ขอบคุณที่ติดต่อ PP BEAUTY",confirmButtonColor:"#c026d3"});setForm({name:"",email:"",subject:"",message:""});};
return <main className="min-h-screen bg-[#fff8fc] px-4 pb-20 pt-32 text-gray-800 dark:bg-[#211627] dark:text-white"><div className="mx-auto max-w-6xl">
<section className="text-center"><span className="rounded-full border border-pink-200 bg-pink-50 px-4 py-1.5 text-xs font-bold tracking-wider text-fuchsia-600">CONTACT PP BEAUTY</span><h1 className="mt-5 text-4xl font-extrabold md:text-5xl">มีคำถามเรื่องความสวยไหม?</h1><p className="mx-auto mt-4 max-w-2xl text-gray-500 dark:text-purple-100/70">สอบถามสินค้า การสั่งซื้อ หรือขอคำแนะนำจากทีมงานได้เลย เราพร้อมช่วยคุณ</p></section>
<section className="mt-10 grid gap-5 md:grid-cols-3">{INFO.map(([i,t,d,s])=><div key={t} className="rounded-2xl border border-pink-100 bg-white p-6 shadow-sm dark:border-purple-900 dark:bg-[#2b1b35]"><div className="text-2xl">{i}</div><h2 className="mt-4 font-bold">{t}</h2><p className="mt-2 text-sm text-fuchsia-600">{d}</p><p className="mt-1 text-xs text-gray-400">{s}</p></div>)}</section>
<section className="mt-10 grid gap-8 lg:grid-cols-2"><div className="rounded-3xl border border-pink-100 bg-white p-8 shadow-sm dark:border-purple-900 dark:bg-[#2b1b35]"><span className="text-sm font-bold text-fuchsia-600">HOW WE CAN HELP</span><h2 className="mt-2 text-2xl font-bold">หัวข้อที่เราช่วยได้</h2><ul className="mt-6 space-y-3">{TOPICS.map(x=><li key={x} className="flex gap-3 text-sm text-gray-600 dark:text-purple-100/70"><span className="text-pink-500">✓</span>{x}</li>)}</ul></div>
<div className="rounded-3xl border border-pink-100 bg-white p-8 shadow-sm dark:border-purple-900 dark:bg-[#2b1b35]"><form onSubmit={submit} className="space-y-5">{[["name","ชื่อของคุณ","กรอกชื่อ"],["email","อีเมล","example@email.com"]].map(([n,l,p])=><div key={n}><label className="mb-2 block text-sm font-medium">{l}</label><input required name={n} value={form[n]} onChange={change} placeholder={p} className="w-full rounded-xl border border-pink-100 bg-pink-50/40 px-4 py-3 outline-none focus:border-fuchsia-400 focus:ring-4 focus:ring-pink-100"/></div>)}<div><label className="mb-2 block text-sm font-medium">หัวข้อ</label><select name="subject" value={form.subject} onChange={change} className="w-full rounded-xl border border-pink-100 bg-pink-50/40 px-4 py-3 outline-none focus:border-fuchsia-400"><option value="">-- เลือกหัวข้อ --</option>{TOPICS.map(x=><option key={x}>{x}</option>)}</select></div><div><label className="mb-2 block text-sm font-medium">ข้อความ</label><textarea required name="message" value={form.message} onChange={change} rows={5} placeholder="พิมพ์ข้อความของคุณ..." className="w-full resize-none rounded-xl border border-pink-100 bg-pink-50/40 px-4 py-3 outline-none focus:border-fuchsia-400"/></div><button disabled={loading} className="w-full rounded-xl bg-gradient-to-r from-pink-500 to-purple-600 py-3.5 font-bold text-white shadow-lg shadow-pink-500/20 disabled:opacity-60">{loading?"กำลังส่ง...":"ส่งข้อความ 💌"}</button></form></div></section>
<div className="mt-10 text-center"><Link href="/" className="text-sm font-medium text-fuchsia-600 hover:text-pink-500">← กลับหน้าหลัก</Link></div>
</div></main>}
